### PR TITLE
Add diff colors

### PR DESCRIPTION
**Pull request by karlhorky**
**Before**

Screen Shot 2021-01-05 at 19 12 04

**After**

Screen Shot 2021-01-05 at 19 11 06

### CODE REVIEW

**Comment by tomasiser** [comment]
Hi! Thank you for the pull request. The theme already contains definitions for DiffAdd, DiffChange, DiffDelete, and DiffText. You added new definitions for diffAdded and diffRemoved, which I had no idea that they existed.

I managed to find [a similar problem in nord-vim](https://github.com/arcticicestudio/nord-vim/issues/66), which they fixed by [linking the highlight groups together](https://github.com/arcticicestudio/nord-vim/pull/67/files). I think that would be the best approach for us as well.

Could you, please, change this PR to the following:
```vim
" Legacy groups for official git.vim and diff.vim syntax
hi! link diffAdded DiffAdd
hi! link diffChanged DiffChange
hi! link diffRemoved DiffDelete
```
and verify that it still works well for you?

**Comment by karlhorky** [comment]
I can verify that this does do something, although I'm not sure if these are the intended colors:

Screen Shot 2021-01-08 at 11 38 11

I will change the PR.

**Comment by karlhorky** [comment]
The colors I previously had are more in line with the colors in real VS Code:

Screen Shot 2021-01-08 at 11 42 25

**Comment by tomasiser** [comment]
Thank you, I agree with you that the background colors look weird. I just tried it in VS Code and they use a much brighter green. In the current color scheme, there is the following colors:

```vim
let s:cdDiffRedDark = {'gui': '#4B1818', 'cterm': s:cterm08, 'cterm256': '52'}
let s:cdDiffRedLight = {'gui': '#6F1313', 'cterm': s:cterm08, 'cterm256': '52'}
let s:cdDiffRedLightLight = {'gui': '#FB0101', 'cterm': s:cterm08, 'cterm256': '09'}
let s:cdDiffGreenDark = {'gui': '#373D29', 'cterm': s:cterm0B, 'cterm256': '237'}
let s:cdDiffGreenLight = {'gui': '#4B5632', 'cterm': s:cterm09, 'cterm256': '58'}
```
and the following highlights:
```vim
call <sid>hi('DiffAdd', {}, s:cdDiffGreenDark, 'none', {})
call <sid>hi('DiffChange', {}, s:cdDiffRedDark, 'none', {})
call <sid>hi('DiffDelete', {}, s:cdDiffRedLight, 'none', {})
call <sid>hi('DiffText', {}, s:cdDiffRedLight, 'none', {})
```
and with the new change, we linked the other highlights to the old ones:
```vim
hi! link diffAdded DiffAdd
hi! link diffChanged DiffChange
hi! link diffRemoved DiffDelete
```

This is how it looks like in VS Code diff view:
image

Do you think you'd be able to replicate this behavior by changing the existing `Diff*` highlights, or do you prefer something a bit different? For example, I think that the `s:cdDiffGreenDark` in `DiffAdd` can be replaced by `s:cdDiffGreenLight`.

**Comment by karlhorky** [comment]
> I have no idea how you got that screenshot from your VS Code?

It was using an editable file in the `Diff (diff)` language mode ( <kbd>ctrl/cmd</kbd>-<kbd>shift</kbd>-<kbd>P</kbd> -> Change Language Mode), which is I suppose closer to the mode that I am using Vim for (diffs inside of the editor during writing Git commit messages).

> Do you think you'd be able to replicate this behavior by changing the existing `Diff*` highlights, or do you prefer something a bit different? For example, I think that the `s:cdDiffGreenDark` in `DiffAdd` can be replaced by `s:cdDiffGreenLight`.

I tried reading the comment a couple of times, but I'm not sure I'm following what you're asking here - you want me to edit the following line as such?

```diff
-call <sid>hi('DiffAdd', {}, s:cdDiffGreenDark, 'none', {})
+call <sid>hi('DiffAdd', {}, s:cdDiffGreenLight, 'none', {})
```

**Comment by tomasiser** [comment]
Yes, that is exactly what I meant. If you could commit that and keep the `hi! link`, it should at least be consistent.

Anyway, I had no idea that there are actually 2 different modes how to view differences in VS Code. So now I am not sure which is better. Maybe, in this special case, it would make sense to let the user choose if they prefer the background color or foreground color diff. Maybe with an option like `g:codedark_use_foreground_diff_colors` that would switch to your proposed foreground colors instead of changing the background.

**Comment by karlhorky** [comment]
Ok, I've done the update.

As for the other option, sounds like it could be reasonable, although I am not experienced enough with Vimscript to know how to do that. This PR can be edited by maintainers though, so if you want to add something, feel free :)

**Comment by tomasiser** [comment]
Whoops, I forgot to merge this. :) Thank you! I think if anyone else wants to update the colors with the extra option, they could make their own PR that I would merge then. :)

**Comment by karlhorky** [comment]
Cool, thanks for the merge!

**Pull request merged**
