### PR TITLE
Fix treesitter function color and add nvim-cmp highlights

### PR DESCRIPTION
**Pull request by David-Else**
Please see https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu. This PR adds those highlights directly.

nvim-cmp-dark-plus

(and also this PR makes the `function` keyword blue in treesitter, as it should be)

### CODE REVIEW

**Comment by tomasiser** [comment]
Thank you for this PR! Merged! :)

**Comment by zhishan** [comment]
Hi @David-Else @tomasiser 

First of all, thanks for your awesome contribution. But I thought, it would be better let you know my case:

I got an error when entering the `vim`:
```
Error detected while processing function <SNR>15_hi:
line    8:
E418: Illegal value: strikethrough
Press ENTER or type command to continue
```

After I removed the line:
```
call <sid>hi('CmpItemAbbrDeprecated', s:cdGray, {}, 'strikethrough', {})
```
It worked as intended. Does it depend on other plugins?

FYI, its latest commit in my host is
```
$ git log
commit 7fe0dc672b20ef62962494560a0bc656fb237346 (HEAD -> master, origin/master, origin/HEAD)
Merge: b75d76f 0edd11c
Author: Tomáš Iser <hello@tomasiser.com>
Date:   Fri Dec 17 14:58:50 2021 +0100

    Merge pull request #63 from zdzislaw-s/zdzislaw-c++-vscode-vs-vim
    
    Changes for better colorization of C++ code
```
Would you please take a look?

**Comment by David-Else** [comment]
I think it is very rare that a terminal does not support `strikethrough`. It does not depend on anything apart from your terminal.

If some kind of check can be done:

IF terminal supports: `call <sid>hi('CmpItemAbbrDeprecated', s:cdGray, {}, 'strikethrough', {})`
ELSE it doesn't: `call <sid>hi('CmpItemAbbrDeprecated', s:cdGray, {}, 'none', {})`

Then it would fix it. Do you have another terminal on your machine? I found this comment that might help with this issue: https://github.com/tmux/tmux/issues/612#issuecomment-280862008

**Comment by zhishan** [comment]
Thanks for you reply. I dig it deeper today and found that it is caused by the statement in `~/.vimrc`:
```
colorscheme codedark
```
It will disappear when using the below:
```
let g:airline_theme = 'codedark'
```

After reading the code, I found that `call <sid>hi` function looks like working as below:
``` 
:hi comment guifg=Blue ctermfg=Red cterm=underline
```
Screenshot from 2022-01-04 23-44-05


But when I set `cterm=strikethrough`, the error: **E418: Illegal value: strikethrough** will be displayed.
Screenshot from 2022-01-04 23-44-22


FYI, my terminal is *terminator* and `echo -e "\e[9mstrikethrough\e[0m"` works as intended.

**Comment by tomasiser** [comment]
Hmm, this looks like a serious problem. Interesting that no one has complained about it so far. Could you try it in a different terminal just to make sure it is really a problem of the terminal and not something deeper in your system?

**Pull request merged**
