### PR TITLE
Changes for better colorization of C++ code

### PR DESCRIPTION
**Pull request by zdzislaw-s**
This pull request to some extend addresses https://github.com/tomasiser/vim-code-dark/issues/40.

For the whole thing to work to the satisfactory level in my environment, I've installed the [TagHighlight plugin](https://github.com/abudden/taghighlight-automirror.git) and:
1) modified these original entries:
```vim
let s:cdFront = {'gui': '#D4D4D4', 'cterm': s:cterm05, 'cterm256': '109'}
let s:cdNonText = {'gui': '#5A5A5A', 'cterm': s:cterm04, 'cterm256': '71'}
let s:cdBlueGreen = {'gui': '#4EC9B0', 'cterm': s:cterm0F, 'cterm256': '36'}
call <sid>hi('NonText', s:cdNonText, s:cdBack, 'none', {})
```

2) added these new ones:
```vim
" C++:
call <sid>hi('CTagsClass', s:cdBlueGreen, {}, 'none', {})
call <sid>hi('CTagsStructure', s:cdBlueGreen, {}, 'none', {})
call <sid>hi('CTagsNamespace', s:cdBlueGreen, {}, 'none', {})
call <sid>hi('CTagsGlobalVariable', s:cdBlueGreen, {}, 'none', {})
call <sid>hi('CTagsDefinedName ', s:cdBlue, {}, 'none', {})
highlight def link CTagsFunction Function
highlight def link CTagsMember Identifier
```

The final result is shown below.
vscode-vim

EDIT:
I've just looked at the PR https://github.com/tomasiser/vim-code-dark/pull/51, which tries to address the same issue (i.e. better syntax highlighting of C++ code) and have some comments.

I had a brief look at the [color_coded plugin](https://github.com/jeaye/color_coded) as an option to follow but dismissed it as a solution. The color_coded plugin uses libclang, which means that the "understanding" of C++ code is much better than when using Exuberant Ctags (TagHighlight requires those) however:
- ATP the setup of color_coded is too involving to my liking, 
- there are too many dependencies that are required for the whole thing to work, and
- I'm not sure whether the impact of constant compilation of C++ code in the background is acceptable for large code bases.

### CODE REVIEW

**Comment by tomasiser** [comment]
Hi, thank you! I had a look at this and #51 and I think it would be perhaps best to merge them together somehow, in case `color_coded` provides some more features than ctags. Do you think you could have a look at that?

By the way, why did you change the terminal color for BlueGreen? :)

**Comment by zdzislaw-s** [comment]
Sure, NP. The merge is not trivial though. #51 redefines several colors/highlight groups and I don't think I'm in position to promote those. OTOH, **adding** new highlight groups is harmless and to everyone's benefit. See my last commit for the result of the merge - comments are welcome ;)

Re: BlueGreen, the color with value `43` was a bit harsh on my eyes so I experimented with other values and settled on `36`. See the screenshot for the comparison of:
VS Code (left), Vim with `BlueGreen == 36` (top-right), Vim with `BlueGreen == 43` (bottom-right). No hard feelings if you prefer to stick to the original value ;)

vscode-vim

**Comment by tomasiser** [comment]
Ok, thank you, I get it! :)

I would probably prefer if we could merge this PR without changing the main colors on lines 69, 93, 118, and 155. You could still have them in your own fork, but I am afraid that changing them for everyone who is using this color scheme could be a change that not everyone would be a fan of.

**Comment by zdzislaw-s** [comment]
As requested, lines 69, 93, 118, and 155 are restored to their original state.

**Comment by tomasiser** [comment]
Hi, sorry for this taking so long, I was conflicted which of the C++ PRs should be merged and then nothing was happening, so I now decided to merge this one. Thank you for your time! :)

**Pull request merged**
