### PR TITLE
Feat: adding variable codedark_transparent #78

### PR DESCRIPTION
**Pull request by saccarosium**
*before*
Screenshot 2022-07-06 at 15 44 26

*after*
Screenshot 2022-07-06 at 15 44 36

### CODE REVIEW

**Comment by tomasiser** [comment]
Hi, this looks like a nice change! How does this compare to #81 ? I will merge your change now but would still be interested if it also fixes #81 ! Thank you!

**Comment by saccarosium** [comment]
I will check it out and see what I can do.

**Comment by saccarosium** [comment]
> Hi, this looks like a nice change! How does this compare to #81 ?

I've checked #81. For what I understood, it wants to make the background transparent so he can use tmux background and use something that change color by what window is focused. 

> I will merge your change now but would still be interested if it also fixes #81 !

I haven't test it but it should work, even better than the fix in #81. When I have my pc I will test this

**Comment by saccarosium** [comment]
I've tested, this PR resolve also #81

**Comment by tomasiser** [comment]
Wonderful, thank you so much!

**Pull request merged**
