### PR TITLE
Git highlighting

### PR DESCRIPTION
**Pull request by hosseintoussi**
This PR adds some git hightlighting:

Before on `:Gcommit`:
image

After:
image

For the choice of colors:
Green is the git staged color, and Red is the not staged color of Git.
For the overflow commit it is highlighted with Red. I chose Red because it is the color that other themes also use for the overflow. 
Commit summary has no color, again like other themes.

### CODE REVIEW

**Comment by tomasiser** [comment]
Hi, looks good, but there is a merge conflict. Could you please resolve the conflict? I am also wondering if light gray color would look better. Thanks!

**Comment by hosseintoussi** [comment]
Hey @tomasiser, sorry been busy lately. I actually have more improvements on this. I will try to spend some time on it this weekend and will also resolve the conflicts.

**Comment by hosseintoussi** [comment]
hey @tomasiser this is ready. Please have a look. Thank you so much 🙏

**Comment by tomasiser** [comment]
Hey I think this is good. Thanks for the contribution!

**Pull request merged**
